### ISSUE TITLE
Support for adding tasks from interfaces

### ISSUE THREAD

**Issue by Nabakamal** [lucaslorentz/durabletask-extensions#21]
Hello. I just stumbled upon this library late last night.  

And, maybe, this is more of a feature request but I don't see a way of adding activities from interfaces in your samples. 

Essentially, to be able to call 

`instanceOfTaskHubWorker.AddTaskActivitiesFromInterface(Type @interface, object activities, bool useFullyQualifiedMethodNames = false)`

I rummaged through the samples but I don't see you have any for the same. What I need is to be able to inject services to my activities and I'm following this article - https://andrewstevens.dev/posts/dependency-injection-durable-task/#:~:text=When%20calling%20AddTaskOrchestrations%20%28%29%20or%20AddTaskActivities%20%28%29%2C%20you,that%20uses%20the%20built%20in.NET%20Core%20dependency%20injection. - to inject a service provider; this works with orchestrations whereas I cannot figure out how to do it for my TaskActivities.

If you have a suggestion on how to use strongly-typed DI-enabled activities then please advise. 

Also, point to note, my orchestrations then call activities so I can inject said services into the orchestrations and pass them down but that'd just be a hack.

**Comment by lucaslorentz** [comment]
> Also, point to note, my orchestrations then call activities so I can inject said services into the orchestrations and pass them down but that'd just be a hack.

Yeah, passing services from orchestrations to activities wouldn't work.

Adding support for that in #22.
